# Generated by Django 3.2.9 on 2021-11-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='pament_id',
            new_name='payment_id',
        ),
    ]
